#!/bin/bash
startidea
echo 1. idea      started

startpostman
echo 2. postman   started

wechat start
echo 3. wechat    started

systemctl start kingbase8d
"/home/witt/kdb/Scripts/javatools.sh" "/home/witt/kdb/ManagerTools/manager" 1>/dev/null 2>&1 &
echo 4. kingbase  started

