#!/bin/bash
# start vm automatically

line=`systemctl status vmware | grep "active (running)"`

echo $line

if [ ! "$line" ]; then
	echo line is not null, its value === $line
else
	echo line is null
fi

