#!/bin/bash
# start or stop wecaht container
case "$1" in 
	start)
		xhost +
		sudo docker start wechat
		;;
	restart)
                xhost +
                sudo docker restart wechat
                ;;
	stop)
		sudo docker stop wechat
		;;
        status)
                sudo docker ps
                ;;
	help)
                echo "wechat Version 1.0"
                echo "This command is used for starting or stoping wechat, or checking the wechat's status."
                echo "Usage: wechat {start | stop | restart | status}"
                ;;
        *)
                echo "Usage: wechat {start | stop | restart | status}"
                ;;
esac
